from __future__ import annotations

from dataclasses import dataclass
from enum import Enum


class ErrorCode(str, Enum):
    WORKFLOW_ERROR = "WORKFLOW_ERROR"
    WORKFLOW_PROJECT_MISMATCH = "WORKFLOW_PROJECT_MISMATCH"
    RUNTIME_NOT_WRITABLE = "RUNTIME_NOT_WRITABLE"
    INVALID_STATE = "INVALID_STATE"
    STATE_INCONSISTENT = "STATE_INCONSISTENT"
    INVALID_GATE = "INVALID_GATE"
    PROTECTED_PATH_MODIFIED = "PROTECTED_PATH_MODIFIED"
    HOOK_UNTRUSTED = "HOOK_UNTRUSTED"
    CODEX_NOT_FOUND = "CODEX_NOT_FOUND"
    CODEX_CONFIG_ERROR = "CODEX_CONFIG_ERROR"
    REVIEW_TIMEOUT = "REVIEW_TIMEOUT"
    REVIEWER_INFRASTRUCTURE_ERROR = "REVIEWER_INFRASTRUCTURE_ERROR"
    REVIEWER_NETWORK_ERROR = "REVIEWER_NETWORK_ERROR"
    REVIEWER_PROCESS_ERROR = "REVIEWER_PROCESS_ERROR"
    REVIEWER_INVALID_OUTPUT = "REVIEWER_INVALID_OUTPUT"
    REVIEW_EVIDENCE_UNAVAILABLE = "REVIEW_EVIDENCE_UNAVAILABLE"
    VERIFICATION_COMMAND_FAILED = "VERIFICATION_COMMAND_FAILED"
    VERIFICATION_INFRASTRUCTURE_ERROR = "VERIFICATION_INFRASTRUCTURE_ERROR"
    VERIFICATION_TIMEOUT = "VERIFICATION_TIMEOUT"
    INTEGRITY_ERROR = "INTEGRITY_ERROR"
    IMPLEMENTER_PROCESS_ERROR = "IMPLEMENTER_PROCESS_ERROR"
    EXECUTION_INTERRUPTED = "EXECUTION_INTERRUPTED"
    PLANNER_NETWORK_ERROR = "PLANNER_NETWORK_ERROR"
    PLANNER_TRANSPORT_ERROR = "PLANNER_TRANSPORT_ERROR"
    PLANNER_SCHEMA_ERROR = "PLANNER_SCHEMA_ERROR"
    PLANNER_PROCESS_ERROR = "PLANNER_PROCESS_ERROR"
    PLAN_TIMEOUT = "PLAN_TIMEOUT"
    SCHEMA_VALIDATION_ERROR = "SCHEMA_VALIDATION_ERROR"
    SCHEMA_VERSION_ERROR = "SCHEMA_VERSION_ERROR"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    LOCKED = "LOCKED"
    PLAN_UNCLEAR = "PLAN_UNCLEAR"
    PLAN_REQUIRED = "PLAN_REQUIRED"
    NOTHING_TO_VALIDATE = "NOTHING_TO_VALIDATE"
    UPDATE_CHECK_ERROR = "UPDATE_CHECK_ERROR"
    UPDATE_DOWNLOAD_ERROR = "UPDATE_DOWNLOAD_ERROR"
    UPDATE_CHECKSUM_ERROR = "UPDATE_CHECKSUM_ERROR"
    UPDATE_SIGNATURE_ERROR = "UPDATE_SIGNATURE_ERROR"
    UPDATE_MANIFEST_ERROR = "UPDATE_MANIFEST_ERROR"
    UPDATE_INSTALL_ERROR = "UPDATE_INSTALL_ERROR"
    UPDATE_SMOKE_TEST_ERROR = "UPDATE_SMOKE_TEST_ERROR"
    UPDATE_ROLLBACK_ERROR = "UPDATE_ROLLBACK_ERROR"
    UPDATE_INCOMPATIBLE = "UPDATE_INCOMPATIBLE"
    UPDATE_DEVELOPMENT_INSTALL = "UPDATE_DEVELOPMENT_INSTALL"
    MCP_OPTIONAL_UNAVAILABLE = "MCP_OPTIONAL_UNAVAILABLE"
    MCP_REQUIRED_UNAVAILABLE = "MCP_REQUIRED_UNAVAILABLE"
    MCP_AUTH_REQUIRED = "MCP_AUTH_REQUIRED"
    MCP_SERVER_ERROR = "MCP_SERVER_ERROR"
    MCP_TRANSPORT_ERROR = "MCP_TRANSPORT_ERROR"
    MCP_DISABLED = "MCP_DISABLED"
    MCP_NOT_CONFIGURED = "MCP_NOT_CONFIGURED"
    BATCH_TOO_LARGE = "BATCH_TOO_LARGE"
    BATCH_TIME_EXHAUSTED = "BATCH_TIME_EXHAUSTED"
    BATCH_REVISION_EXHAUSTED = "BATCH_REVISION_EXHAUSTED"
    BATCH_INTERRUPTED = "BATCH_INTERRUPTED"
    USAGE_ERROR = "USAGE_ERROR"
    AUTHORIZATION_REQUIRED = "AUTHORIZATION_REQUIRED"
    OPERATION_CONFLICT = "OPERATION_CONFLICT"
    PROJECT_SCOPE_VIOLATION = "PROJECT_SCOPE_VIOLATION"
    PLAN_REBASELINE_REQUIRED = "PLAN_REBASELINE_REQUIRED"
    STALE_WORKFLOW_SHA = "STALE_WORKFLOW_SHA"
    STALE_STATE_SHA = "STALE_STATE_SHA"
    INVALID_ARTIFACT = "INVALID_ARTIFACT"
    FORBIDDEN_PLAN_CHANGE = "FORBIDDEN_PLAN_CHANGE"
    COMPLETION_CONTRACT_CHANGE_REQUIRES_REBUILD = "COMPLETION_CONTRACT_CHANGE_REQUIRES_REBUILD"
    PLAN_AMEND_INTEGRITY_ERROR = "PLAN_AMEND_INTEGRITY_ERROR"
    PLAN_AMEND_ROLLBACK_FAILED = "PLAN_AMEND_ROLLBACK_FAILED"
    PLAN_REVISION_INVALID = "PLAN_REVISION_INVALID"
    SUPERSESSION_INVALID = "SUPERSESSION_INVALID"
    TRANSACTION_RECOVERY_REQUIRED = "TRANSACTION_RECOVERY_REQUIRED"


@dataclass(slots=True)
class CwError(RuntimeError):
    message: str
    code: ErrorCode = ErrorCode.WORKFLOW_ERROR
    hint: str | None = None
    details: str | None = None
    exit_code: int = 1

    def __str__(self) -> str:
        return self.message


class HumanActionRequired(CwError):
    def __init__(self, message: str, *, hint: str | None = None) -> None:
        super().__init__(message, ErrorCode.WORKFLOW_ERROR, hint, exit_code=3)
